stages:
  - mavenbuild
  - maventest
  - autodeploy

maven-build:
    stage: mavenbuild
    tags:
      - shell
    script:
      - cd Backend/exercyze
      - mvn package -B
      - ls target

maven-test:
    stage: maventest
    tags:
      - shell
    script:
      - cd Backend/exercyze
      - mvn test
    artifacts:
      paths:
        - Backend/exercyze/target/*.jar

autoDeploy:
  stage: autodeploy
  tags: 
    - shell
  script: 
    - cd Backend/exercyze
    - mvn test
    - ls target
    - sudo mv target/*.jar /target/web-demo.jar
    - sudo systemctl stop systemd-web-demo
    - sudo systemctl start systemd-web-demo
